### ISSUE TITLE
Port "Perception Pipeline Tutorial" tutorial 

### ISSUE THREAD

**Issue by bostoncleek** [moveit/moveit2_tutorials#25]
Port tutorial to ROS2.

**Comment by JeisonUR** [comment]
haven't it been migrated yet? is there any progress?

**Comment by mikeferguson** [comment]
Actual loading of sensor data is implemented here: https://github.com/ros-planning/moveit2/pull/1387

I'll probably circle back in about a week and try a first pass of cleaning up this tutorial

**Comment by 130s** [comment]
More discussion is happening in https://github.com/ros-planning/moveit2_tutorials/issues/583 about the same issue. Suggest to close this?

**Comment by tylerjw** [comment]
Not ported: https://moveit.picknik.ai/main/doc/examples/perception_pipeline/perception_pipeline_tutorial.html

**Comment by sea-bass** [comment]
Closed by #906
