### ISSUE TITLE
flickering robot and NO PLANNING LIBRARY LOADED error with the demo launch file

### ISSUE THREAD

**Issue by hassan-tht** [moveit/moveit2_tutorials#536]
### Description
On a freshly installed `Ubuntu` 22.04 on a Lenovo-ideapad-700-15ISK machine, I installed `ROS` humble (by: `sudo apt install ros-humble-desktop-full`) and `moveit2` (from source). Running the `demo` launch file from `moveit2_tutorials` package, the robot is flickering inside `rviz` and the `OMPL` is not loading as shown below:

![flickering robot in rviz gif](https://raw.githubusercontent.com/hassan-tht/trbl/main/351F2D72-FD21-4BDE-9677-30AA268DE78C.gif)

### Your environment
* ROS Distro: Humble
* OS Version: Ubuntu 22.04
* System: 5.15.0-43-generic # 46 - Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Built from source
* git commit: 2bf3e23

### Notes
1. This behaviour is not consistent; sometimes it happens and sometimes it does not. Moreover, sometimes it runs normally and suddenly it does that again (I can't find a pattern though).
2. Trying to remove `ROS`/`MoveIt` or even completely uninstall `Ubuntu` (with the disk formatted) does not solve the problem. This has been tried 5 times now.
3. On the machine, there's nothing installed but `ROS` and `moveit.` In the terminal, after the clean install of `Ubuntu,` these are exactly the commands typed in the terminal and nothing else:
```bash
sudo apt update && sudo apt install locales
sudo locale-gen en_US en_US.UTF-8
sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export LANG=en_US.UTF-8
locale
apt-cache policy | grep universe
sudo apt update && sudo apt install curl gnupg lsb-release
sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
sudo apt update
sudo apt upgrade
sudo apt install ros-humble-desktop-full
source /opt/ros/humble/setup.bash
sudo apt update
sudo apt dist-upgrade
sudo apt install python3-rosdep 
sudo rosdep init
rosdep update
sudo apt install build-essential 
sudo apt install cmake
sudo apt install git
sudo apt install libbullet-dev 
sudo apt install python3-colcon-common-extensions 
sudo apt install python3-flake8
sudo apt install python3-pip 
sudo apt install python3-pytest-cov 
sudo apt install python3-setuptools
sudo apt install python3-vcstool 
sudo apt install wget
python3 -m pip install -U argcomplete 
python3 -m pip install -U flake8-blind-except 
python3 -m pip install -U flake8-builtins 
python3 -m pip install -U flake8-class-newline 
python3 -m pip install -U flake8-comprehensions
python3 -m pip install -U flake8-deprecated 
python3 -m pip install -U flake8-docstrings
python3 -m pip install -U flake8-import-order 
python3 -m pip install -U flake8-quotes
python3 -m pip install -U pytest-repeat
python3 -m pip install -U pytest-rerunfailures 
python3 -m pip install -U pytest
mkdir -p moveit_ws/src
cd moveit_ws/src
git clone https://github.com/ros-planning/moveit2.git -b $ROS_DISTRO
for repo in moveit2/moveit2.repos $(f="moveit2/moveit2_$ROS_DISTRO.repos"; test -r $f && echo $f); do vcs import < "$repo"; done
rosdep install -r --from-paths . --ignore-src --rosdistro $ROS_DISTRO
cd ..
colcon build --event-handlers desktop_notification- status- --cmake-args -DCMAKE_BUILD_TYPE=Release
sudo apt install python3-colcon-mixin
colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
colcon mixin update default
cd src/
git clone https://github.com/ros-planning/moveit2_tutorials -b humble --depth 1
vcs import < moveit2_tutorials/moveit2_tutorials.repos
sudo apt update && rosdep install -r --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y
cd ..
colcon build --mixin release
source install/setup.bash 
ros2 launch moveit2_tutorials demo.launch.py 
```

**Comment by hassan-tht** [comment]
and whenever I change the `Fixed Frame` in the `Global Options` inside `rviz` to anything but the `panda_link0` e.g., `World`, (whether this problem is happening or not) `rviz` crashes and I get the error below:

```bash
[rviz2-1] [INFO] [1667068704.341469427] [interactive_marker_display_94715816956032]: Target frame is now world
[ERROR] [rviz2-1]: process has died [pid 109811, exit code -11, cmd '/opt/ros/humble/lib/rviz2/rviz2 -d /home/hassan/moveit_ws/install/moveit2_tutorials/share/moveit2_tutorials/launch/panda_moveit_config_demo.rviz --ros-args -r __node:=rviz2 --params-file /tmp/launch_params_tenikcki --params-file /tmp/launch_params_fsz3_v6g --params-file /tmp/launch_params_61o2bj_r --params-file /tmp/launch_params_tb4uzdbb'].
```

**Comment by AndyZe** [comment]
You might try adjusting your graphics drivers. For example, does your computer have an NVidia GPU? Then switch to an nvidia driver.

Are you already using an Nvidia driver? Then switch to `nouveau`, the open-source driver.

**Comment by hassan-tht** [comment]
Thanks, yes it does and I'm using `nouveau`

**Comment by hassan-tht** [comment]
I tried switching from nouveau to the nvidia driver to double check, but I still have the same problem

**Comment by AndyZe** [comment]
Another question: have you tried switching to Cyclone DDS? A lot of users (including me) report trouble with the default DDS. To switch, just enter this:

`export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp`

Or add it to your ~/.bashrc so it's sourced for every terminal.

**Comment by sea-bass** [comment]
> Another question: have you tried switching to Cyclone DDS? A lot of users (including me) report trouble with the default DDS. To switch, just enter this:
> 
> `export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp`
> 
> Or add it to your ~/.bashrc so it's sourced for every terminal.

If you try this, you should also install it first:

```
sudo apt-get install ros-humble-rmw-cyclonedds-cpp
```

**Comment by hassan-tht** [comment]
Thanks, I already tried this before but didn't solve the problem (and actually the reason I tried this is that all the problems started with this error while working with something else: RTPS_MSG_IN Error]  Problem reserving CacheChange in reader

**Comment by AndyZe** [comment]
Can you please try the `main` branch of moveit2_tutorials? It should work great on both Rolling and Humble. Looks like the humble branch has not been updated much (and I'm not sure why it even exists yet).

**Comment by hassan-tht** [comment]
Thanks again, but switching to `main` didn't solve the problem.

**Comment by mrmorten** [comment]
See issue #1049 for (probable) solution and #1782 for my debug.

**Comment by henningkayser** [comment]
@hassan-tht can you comment if the mentioned PRs have fixed your issue, and close it in that case?

**Comment by tylerjw** [comment]
Is there a chance you have multiple publishers to `/robot_state`?
