### ISSUE TITLE
moveit colcon build fail CMake Error version

### ISSUE THREAD

**Issue by gsoto-tellez** [moveit/moveit2_tutorials#888]
I am running Ubuntu 20.04 on a Jetson Xavier, ROS2 Foxy and am trying to setup MoveIt following the documentation outlined here: 
 
https://moveit.picknik.ai/main/doc/tutorials/getting_started/getting_started.html

However after running colcon build --mixin release I got this error:

objpkjnfp@teambot-desktop:~/ws_moveit$ colcon build --mixin release
[3.652s] WARNING:colcon.colcon_core.package_selection:Some selected packages are already built in one or more underlay workspaces:
	'moveit_planners' is in: /opt/ros/foxy
	'moveit_ros_warehouse' is in: /opt/ros/foxy
	'moveit_kinematics' is in: /opt/ros/foxy
	'moveit_simple_controller_manager' is in: /opt/ros/foxy
	'moveit_ros_move_group' is in: /opt/ros/foxy
	'moveit_ros_visualization' is in: /opt/ros/foxy
	'moveit_ros_planning_interface' is in: /opt/ros/foxy
If a package in a merged underlay workspace is overridden and it installs headers, then all packages in the overlay must sort their include directories by workspace order. Failure to do so may result in build failures or undefined behavior at run time.
If the overridden package is used by another package in any underlay, then the overriding package in the overlay must be API and ABI compatible or undefined behavior at run time may occur.

If you understand the risks and want to override a package anyways, add the following to the command line:
	--allow-overriding moveit_kinematics moveit_planners moveit_ros_move_group moveit_ros_planning_interface moveit_ros_visualization moveit_ros_warehouse moveit_simple_controller_manager

This may be promoted to an error in a future release of colcon-override-check.
Starting >>> moveit_common
Starting >>> moveit_msgs
Starting >>> moveit_configs_utils                                             
Starting >>> moveit_resources_panda_description                                   
--- stderr: moveit_common                                                                        
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.22 or higher is required.  You are running version 3.16.3

---
Failed   <<< moveit_common [2.20s, exited with code 1]
Aborted  <<< moveit_resources_panda_description [2.04s]                        
Aborted  <<< moveit_configs_utils [4.06s]                                      
Aborted  <<< moveit_msgs [8min 46s]                                          
                                       
Summary: 0 packages finished [8min 48s]
  1 package failed: moveit_common
  3 packages aborted: moveit_configs_utils moveit_msgs moveit_resources_panda_description
  1 package had stderr output: moveit_common
  65 packages not processed

When I ran:
sudo apt update && rosdep install -r --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y

I go these errors too:

objpkjnfp@teambot-desktop:~/ws_moveit/src$ sudo apt update && rosdep install -r --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y
Get:1 file:/var/nv-tensorrt-local-repo-l4t-8.5.2-cuda-11.4  InRelease [1,575 B]
Hit:2 http://repo.ros2.org/ubuntu/main focal InRelease
Hit:3 http://packages.ros.org/ros2/ubuntu focal InRelease
Hit:4 http://packages.osrfoundation.org/gazebo/ubuntu-stable focal InRelease                       
Hit:5 http://www.phidgets.com/debian bullseye InRelease                                            
Get:1 file:/var/nv-tensorrt-local-repo-l4t-8.5.2-cuda-11.4  InRelease [1,575 B]                    
Hit:8 https://repo.download.nvidia.com/jetson/common r35.2 InRelease                               
Hit:9 http://ports.ubuntu.com/ubuntu-ports focal InRelease                                         
Get:10 https://repo.download.nvidia.com/jetson/t194 r35.2 InRelease [2,547 B]                      
Hit:6 https://packages.microsoft.com/repos/vscode stable InRelease                                 
Hit:11 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease                                
Hit:7 https://packagecloud.io/dirk-thomas/colcon/ubuntu focal InRelease
Get:12 https://apt.kitware.com/ubuntu focal InRelease [15.5 kB]
Hit:13 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
Hit:14 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
Err:12 https://apt.kitware.com/ubuntu focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1A127079A92F09ED
Reading package lists... Done
W: GPG error: https://apt.kitware.com/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1A127079A92F09ED
E: The repository 'https://apt.kitware.com/ubuntu focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

I updated my cmake to the newest version 3.16.3 for Ubuntu 20.04. Do i need to use Ubuntu 22.04 to use MoveIt?

**Comment by tanmayyb** [comment]
Same issue here, top answer from this [AskUbuntu post](https://askubuntu.com/questions/829310/how-to-upgrade-cmake-in-ubuntu) warns against uninstalling CMake because it will break ROS.
