### ISSUE TITLE
I would like to generate multiple solutions for each task generated in Task Constructor

### ISSUE THREAD

**Issue by dogukanyilmazerkba** [moveit/moveit2_tutorials#889]
Title, I am new to moveit2 and I want to generate multiple solutions for my stages. When I run example panda files, for some movements it generates multiple solutions. But when I write the same code for my project it only generates single solution. How can I get more than one?

![JXlan](https://github.com/ros-planning/moveit2_tutorials/assets/165284994/9fbd9a51-af51-40e3-861e-3da91e170f98)

### Your environment
* ROS2 Distro: IRON
* OS Version: e.g. Ubuntu 22.04
* Source or Binary build? Source
* If binary, which release version?
* If source, which git commit or tag? Moveit's itself

**Comment by mikeferguson** [comment]
Iron is now EOL (also, for customizing things, you'll find there is a lot more help available on robotics.stackexchange.com than posting to GitHub tickets)
