### ISSUE TITLE
build fails : plan has no member trajectory it should be "trajectory_" 

### ISSUE THREAD

**Issue by robintomar1** [moveit/moveit2_tutorials#895]
Ubuntu 22.04
Ros2 humble

https://github.com/ros-planning/moveit2_tutorials/blob/21a45aac13f64777c4ecc4cf33136667661d1e55/doc/tutorials/planning_around_objects/hello_moveit.cpp#L107

**Comment by rotematari** [comment]
got the same eror

**Comment by sea-bass** [comment]
If you're using Humble, you should use the `humble` branch of this tutorial. If you see here, the `_` is present:
https://github.com/moveit/moveit2_tutorials/blob/humble/doc/tutorials/planning_around_objects/hello_moveit.cpp#L106
