### ISSUE TITLE
Fail to generate collision matrix

### ISSUE THREAD

**Issue by LeonYo153** [moveit/moveit2_tutorials#903]
Fail to generate collision matrix

Overview of your issue here.

### Your environment
* ROS Distro: Humble
* OS Version: e.g. Ubuntu 22.04
* Binary

### Steps to reproduce
I tried to use a existed urdf file to set up a moveit config. Then I used the self collision checking and wanted to generate a collision matrix.

### Expected behaviour
There should be a  result table shows the pairs of links that have been identified as either safe or unsafe to disable from collision checking.

### Backtrace or Console output
No such result shown in the table.

![image](https://github.com/moveit/moveit2_tutorials/assets/166822065/83ba8ab2-e45c-4c40-872a-e7df5f1d8b14)
[moveit_setup_assistant-1] [INFO] [1714740288.778121285] [collision_updater]: Statistics:
[moveit_setup_assistant-1] [INFO] [1714740288.778136304] [collision_updater]: Total Links : 19
[moveit_setup_assistant-1] [INFO] [1714740288.778151960] [collision_updater]: Total possible collisions : 171.000000
[moveit_setup_assistant-1] [INFO] [1714740288.778159488] [collision_updater]: Always in collision : 0
[moveit_setup_assistant-1] [INFO] [1714740288.778165421] [collision_updater]: Never in collision : 0
[moveit_setup_assistant-1] [INFO] [1714740288.778173857] [collision_updater]: Default in collision : 0
[moveit_setup_assistant-1] [INFO] [1714740288.778180547] [collision_updater]: Adjacent links disabled : 0
[moveit_setup_assistant-1] [INFO] [1714740288.778186794] [collision_updater]: Sometimes in collision : 171
[moveit_setup_assistant-1] [INFO] [1714740288.778192584] [collision_updater]: TOTAL DISABLED : 0
[moveit_setup_assistant-1] [INFO] [1714740288.778287022] [moveit_setup_assistant.Self-Collisions]: Thread complete 0

**Comment by mikeferguson** [comment]
Humble was very out of date for Debians for quite some time - a new release has been pushed.
