### ISSUE TITLE
Parameter Type Exception in demo.launch.python

### ISSUE THREAD

**Issue by Santi-13** [moveit/moveit2_tutorials#910]
### Description

I'm following the MoveIt2 tutorials and have encountered an issue when running the `demo.launch.python` file from the `moveit2_tutorials` package. Despite following all the steps in the quickstart guide, I receive a warning in RViz about "Requesting initial scene failed". The terminal log indicates a problem with a parameter type mismatch.

### Your environment
* ROS Distro: Iron
* OS Version: Ubuntu 22.04
* Source build

### Steps to reproduce
Just followed the instructions on the MoveIt Quickstart in RViz(https://moveit.picknik.ai/main/doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.html#moveit-quickstart-in-rviz) tutorial up to step 1. Where I noticed that the planning scene reported "Requesting initial scene failed"

### Backtrace or Console output
lt logging verbosity is set to INFO
[INFO] [rviz2-1]: process started with pid [43563]
[INFO] [static_transform_publisher-2]: process started with pid [43565]
[INFO] [robot_state_publisher-3]: process started with pid [43567]
[INFO] [move_group-4]: process started with pid [43569]
[INFO] [ros2_control_node-5]: process started with pid [43571]
[INFO] [spawner-6]: process started with pid [43573]
[INFO] [spawner-7]: process started with pid [43575]
[INFO] [spawner-8]: process started with pid [43577]
[static_transform_publisher-2] [INFO] [1717116430.267242645] [static_transform_publisher]: Spinning until stopped - publishing transform
[static_transform_publisher-2] translation: ('0.000000', '0.000000', '0.000000')
[static_transform_publisher-2] rotation: ('0.000000', '0.000000', '0.000000', '1.000000')
[static_transform_publisher-2] from 'world' to 'base_link'
[ros2_control_node-5] [INFO] [1717116430.321668594] [controller_manager]: Subscribing to '/robot_description' topic for robot description.
[ros2_control_node-5] [INFO] [1717116430.321965845] [controller_manager]: update rate is 1000 Hz
[ros2_control_node-5] [INFO] [1717116430.322171145] [controller_manager]: RT kernel is recommended for better performance
[robot_state_publisher-3] [INFO] [1717116430.339275418] [robot_state_publisher]: got segment base_link
[robot_state_publisher-3] [INFO] [1717116430.339402577] [robot_state_publisher]: got segment bracelet_link
[robot_state_publisher-3] [INFO] [1717116430.339415228] [robot_state_publisher]: got segment end_effector_link
[robot_state_publisher-3] [INFO] [1717116430.339421988] [robot_state_publisher]: got segment forearm_link
[robot_state_publisher-3] [INFO] [1717116430.339427778] [robot_state_publisher]: got segment half_arm_1_link
[robot_state_publisher-3] [INFO] [1717116430.339433451] [robot_state_publisher]: got segment half_arm_2_link
[robot_state_publisher-3] [INFO] [1717116430.339438964] [robot_state_publisher]: got segment robotiq_85_base_link
[robot_state_publisher-3] [INFO] [1717116430.339444808] [robot_state_publisher]: got segment robotiq_85_left_finger_link
[robot_state_publisher-3] [INFO] [1717116430.339450268] [robot_state_publisher]: got segment robotiq_85_left_finger_tip_link
[robot_state_publisher-3] [INFO] [1717116430.339455829] [robot_state_publisher]: got segment robotiq_85_left_inner_knuckle_link
[robot_state_publisher-3] [INFO] [1717116430.339461394] [robot_state_publisher]: got segment robotiq_85_left_knuckle_link
[robot_state_publisher-3] [INFO] [1717116430.339466937] [robot_state_publisher]: got segment robotiq_85_right_finger_link
[robot_state_publisher-3] [INFO] [1717116430.339472370] [robot_state_publisher]: got segment robotiq_85_right_finger_tip_link
[robot_state_publisher-3] [INFO] [1717116430.339477875] [robot_state_publisher]: got segment robotiq_85_right_inner_knuckle_link
[robot_state_publisher-3] [INFO] [1717116430.339483219] [robot_state_publisher]: got segment robotiq_85_right_knuckle_link
[robot_state_publisher-3] [INFO] [1717116430.339488760] [robot_state_publisher]: got segment shoulder_link
[robot_state_publisher-3] [INFO] [1717116430.339494496] [robot_state_publisher]: got segment spherical_wrist_1_link
[robot_state_publisher-3] [INFO] [1717116430.339500131] [robot_state_publisher]: got segment spherical_wrist_2_link
[robot_state_publisher-3] [INFO] [1717116430.339518428] [robot_state_publisher]: got segment world
[ros2_control_node-5] [INFO] [1717116430.339811378] [controller_manager]: Received robot description from topic.
[ros2_control_node-5] [INFO] [1717116430.340566566] [resource_manager]: Loading hardware 'KortexMultiInterfaceHardware' 
[ros2_control_node-5] [INFO] [1717116430.342048482] [resource_manager]: Initialize hardware 'KortexMultiInterfaceHardware' 
[ros2_control_node-5] [WARN] [1717116430.342091176] [mock_generic_system]: Parameter 'fake_sensor_commands' has been deprecated from usage. Use'mock_sensor_commands' instead.
[ros2_control_node-5] [WARN] [1717116430.342141091] [mock_generic_system]: Parsing of optional initial interface values failed or uses a deprecated format. Add initial values for every state interface in the ros2_control.xacro. For example: 
[ros2_control_node-5] <state_interface name="velocity"> 
[ros2_control_node-5]   <param name="initial_value">0.0</param> 
[ros2_control_node-5] </state_interface>
[ros2_control_node-5] [INFO] [1717116430.342161246] [resource_manager]: Successful initialization of hardware 'KortexMultiInterfaceHardware'
[ros2_control_node-5] [INFO] [1717116430.342197198] [resource_manager]: Loading hardware 'RobotiqGripperHardwareInterface' 
[ros2_control_node-5] [INFO] [1717116430.342214023] [resource_manager]: Initialize hardware 'RobotiqGripperHardwareInterface' 
[ros2_control_node-5] [WARN] [1717116430.342231196] [mock_generic_system]: Parameter 'fake_sensor_commands' has been deprecated from usage. Use'mock_sensor_commands' instead.
[ros2_control_node-5] [INFO] [1717116430.342264075] [resource_manager]: Successful initialization of hardware 'RobotiqGripperHardwareInterface'
[ros2_control_node-5] [INFO] [1717116430.342356900] [resource_manager]: 'configure' hardware 'RobotiqGripperHardwareInterface' 
[ros2_control_node-5] [INFO] [1717116430.342372160] [resource_manager]: Successful 'configure' of hardware 'RobotiqGripperHardwareInterface'
[ros2_control_node-5] [INFO] [1717116430.342389600] [resource_manager]: 'activate' hardware 'RobotiqGripperHardwareInterface' 
[ros2_control_node-5] [INFO] [1717116430.342401851] [resource_manager]: Successful 'activate' of hardware 'RobotiqGripperHardwareInterface'
[ros2_control_node-5] [INFO] [1717116430.342414096] [resource_manager]: 'configure' hardware 'KortexMultiInterfaceHardware' 
[ros2_control_node-5] [INFO] [1717116430.342424631] [resource_manager]: Successful 'configure' of hardware 'KortexMultiInterfaceHardware'
[ros2_control_node-5] [INFO] [1717116430.342444807] [resource_manager]: 'activate' hardware 'KortexMultiInterfaceHardware' 
[ros2_control_node-5] [INFO] [1717116430.342455233] [resource_manager]: Successful 'activate' of hardware 'KortexMultiInterfaceHardware'
[ros2_control_node-5] [INFO] [1717116430.438406712] [controller_manager]: Received robot description from topic.
[ros2_control_node-5] [WARN] [1717116430.438470707] [controller_manager]: ResourceManager has already loaded an urdf file. Ignoring attempt to reload a robot description file.
[move_group-4] [INFO] [1717116430.451192404] [move_group.moveit.moveit.ros.rdf_loader]: Loaded robot model in 0.0864216 seconds
[move_group-4] [INFO] [1717116430.451422921] [move_group.moveit.moveit.core.robot_model]: Loading robot model 'gen3'...
[move_group-4] [INFO] [1717116430.451461115] [move_group.moveit.moveit.core.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[move_group-4] [INFO] [1717116430.659259292] [move_group.moveit.moveit.kinematics.kdl_kinematics_plugin]: Joint weights for group 'manipulator': 1 1 1 1 1 1 1
[rviz2-1] [INFO] [1717116430.998265435] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [INFO] [1717116430.998437713] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[ros2_control_node-5] [INFO] [1717116431.006342967] [controller_manager]: Loading controller 'joint_state_broadcaster'
[ros2_control_node-5] [INFO] [1717116431.031933405] [controller_manager]: Loading controller 'joint_trajectory_controller'
[rviz2-1] [INFO] [1717116431.032907074] [rviz2]: Stereo is NOT SUPPORTED
[ros2_control_node-5] [WARN] [1717116431.055330231] [joint_trajectory_controller]: "allow_nonzero_velocity_at_trajectory_end" is set to false. (The default behavior changed to false, and trajectories might get discarded.)
[spawner-6] [INFO] [1717116431.069477284] [spawner_joint_state_broadcaster]: Loaded joint_state_broadcaster
[ros2_control_node-5] [INFO] [1717116431.071472102] [controller_manager]: Configuring controller 'joint_state_broadcaster'
[ros2_control_node-5] [INFO] [1717116431.071659532] [joint_state_broadcaster]: 'joints' or 'interfaces' parameter is empty. All available state interfaces will be published
[spawner-6] [INFO] [1717116431.086554749] [spawner_joint_state_broadcaster]: Configured and activated joint_state_broadcaster
[spawner-7] [INFO] [1717116431.088339292] [spawner_joint_trajectory_controller]: Loaded joint_trajectory_controller
[ros2_control_node-5] [INFO] [1717116431.090713137] [controller_manager]: Configuring controller 'joint_trajectory_controller'
[ros2_control_node-5] [INFO] [1717116431.091019634] [joint_trajectory_controller]: No specific joint names are used for command interfaces. Using 'joints' parameter.
[ros2_control_node-5] [INFO] [1717116431.091072862] [joint_trajectory_controller]: Command interfaces are [position] and state interfaces are [position velocity].
[ros2_control_node-5] [INFO] [1717116431.091096769] [joint_trajectory_controller]: Using 'splines' interpolation method.
[ros2_control_node-5] [INFO] [1717116431.095446036] [joint_trajectory_controller]: Action status changes will be monitored at 20.00 Hz.
[spawner-7] [INFO] [1717116431.112678313] [spawner_joint_trajectory_controller]: Configured and activated joint_trajectory_controller
[ros2_control_node-5] [INFO] [1717116431.179178837] [controller_manager]: Loading controller 'robotiq_gripper_controller'
[spawner-8] [INFO] [1717116431.192488478] [spawner_robotiq_gripper_controller]: Loaded robotiq_gripper_controller
[ros2_control_node-5] [INFO] [1717116431.194005894] [controller_manager]: Configuring controller 'robotiq_gripper_controller'
[ros2_control_node-5] [INFO] [1717116431.194126287] [robotiq_gripper_controller]: Action status changes will be monitored at 20Hz.
[spawner-8] [INFO] [1717116431.202498753] [spawner_robotiq_gripper_controller]: Configured and activated robotiq_gripper_controller
[rviz2-1] [WARN] [1717116431.260191277] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[INFO] [spawner-6]: process has finished cleanly [pid 43573]
[INFO] [spawner-7]: process has finished cleanly [pid 43575]
[move_group-4] [INFO] [1717116431.304570866] [move_group.moveit.moveit.ros.planning_scene_monitor]: Publishing maintained planning scene on 'monitored_planning_scene'
[move_group-4] [INFO] [1717116431.304844759] [move_group.moveit.moveit.ros.moveit_cpp]: Listening to 'joint_states' for joint states
[move_group-4] [INFO] [1717116431.306355323] [move_group.moveit.moveit.ros.current_state_monitor]: Listening to joint states on topic 'joint_states'
[move_group-4] [INFO] [1717116431.306986845] [move_group.moveit.moveit.ros.planning_scene_monitor]: Listening to '/attached_collision_object' for attached collision objects
[move_group-4] [INFO] [1717116431.307017748] [move_group.moveit.moveit.ros.planning_scene_monitor]: Stopping existing planning scene publisher.
[move_group-4] [INFO] [1717116431.307231710] [move_group.moveit.moveit.ros.planning_scene_monitor]: Stopped publishing maintained planning scene.
[move_group-4] [INFO] [1717116431.307762807] [move_group.moveit.moveit.ros.planning_scene_monitor]: Publishing maintained planning scene on 'monitored_planning_scene'
[move_group-4] [INFO] [1717116431.307895727] [move_group.moveit.moveit.ros.planning_scene_monitor]: Starting planning scene monitor
[move_group-4] [INFO] [1717116431.308419556] [move_group.moveit.moveit.ros.planning_scene_monitor]: Listening to '/planning_scene'
[move_group-4] [INFO] [1717116431.308458979] [move_group.moveit.moveit.ros.planning_scene_monitor]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
[move_group-4] [INFO] [1717116431.309781285] [move_group.moveit.moveit.ros.planning_scene_monitor]: Listening to 'collision_object'
[move_group-4] [INFO] [1717116431.310573730] [move_group.moveit.moveit.ros.planning_scene_monitor]: Listening to 'planning_scene_world' for planning scene world geometry
[move_group-4] [WARN] [1717116431.312490496] [move_group.moveit.moveit.ros.occupancy_map_monitor]: Resolution not specified for Octomap. Assuming resolution = 0.1 instead
[move_group-4] [ERROR] [1717116431.312532701] [move_group.moveit.moveit.ros.occupancy_map_monitor]: No 3D sensor plugin(s) defined for octomap updates
[rviz2-1] Warning: class_loader.impl: SEVERE WARNING!!! A namespace collision has occurred with plugin factory for class rviz_default_plugins::displays::InteractiveMarkerDisplay. New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
[rviz2-1]          at line 321 in /opt/ros/iron/include/class_loader/class_loader/class_loader_core.hpp
[INFO] [spawner-8]: process has finished cleanly [pid 43577]
[move_group-4] terminate called after throwing an instance of 'rclcpp::ParameterTypeException'
[move_group-4]   what():  expected [string_array] got [string]
[move_group-4] Stack trace (most recent call last):
[move_group-4] #17   Object "", at 0xffffffffffffffff, in 
[move_group-4] #16   Object "/home/sanmaster/ws_moveit/install/moveit_ros_move_group/lib/moveit_ros_move_group/move_group", at 0x601628faa204, in _start
[move_group-4] #15   Source "../csu/libc-start.c", line 392, in __libc_start_main_impl [0x79233a029e3f]
[move_group-4] #14   Source "../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main [0x79233a029d8f]
[move_group-4] #13   Object "/home/sanmaster/ws_moveit/install/moveit_ros_move_group/lib/moveit_ros_move_group/move_group", at 0x601628fa91c3, in main
[move_group-4] #12   Object "/home/sanmaster/ws_moveit/install/moveit_ros_planning/lib/libmoveit_cpp.so.2.9.0", at 0x79233aebe6a7, in moveit_cpp::MoveItCpp::MoveItCpp(std::shared_ptr<rclcpp::Node> const&, moveit_cpp::MoveItCpp::Options const&)
[move_group-4] #11   Object "/home/sanmaster/ws_moveit/install/moveit_ros_planning/lib/libmoveit_cpp.so.2.9.0", at 0x79233aebd5cb, in moveit_cpp::MoveItCpp::loadPlanningPipelines(moveit_cpp::MoveItCpp::PlanningPipelineOptions const&)
[move_group-4] #10   Object "/home/sanmaster/ws_moveit/install/moveit_ros_planning/lib/libmoveit_planning_pipeline_interfaces.so.2.9.0", at 0x79233a6f8fab, in moveit::planning_pipeline_interfaces::createPlanningPipelineMap(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::shared_ptr<moveit::core::RobotModel const> const&, std::shared_ptr<rclcpp::Node> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
[move_group-4] #9    Object "/home/sanmaster/ws_moveit/install/moveit_ros_planning/lib/libmoveit_planning_pipeline.so.2.9.0", at 0x79233a66efc5, in planning_pipeline::PlanningPipeline::PlanningPipeline(std::shared_ptr<moveit::core::RobotModel const> const&, std::shared_ptr<rclcpp::Node> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
[move_group-4] #8    Object "/home/sanmaster/ws_moveit/install/moveit_ros_planning/lib/libmoveit_planning_pipeline.so.2.9.0", at 0x79233a6b063d, in planning_pipeline_parameters::ParamListener::declare_params()
[move_group-4] #7    Object "/opt/ros/iron/lib/librclcpp.so", at 0x79233a8d9869, in 
[move_group-4] #6    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x79233a4ae4d7, in __cxa_throw
[move_group-4] #5    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x79233a4ae276, in std::terminate()
[move_group-4] #4    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x79233a4ae20b, in 
[move_group-4] #3    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x79233a4a2b9d, in 
[move_group-4] #2    Source "./stdlib/abort.c", line 79, in abort [0x79233a0287f2]
[move_group-4] #1    Source "../sysdeps/posix/raise.c", line 26, in raise [0x79233a042475]
[move_group-4] #0  | Source "./nptl/pthread_kill.c", line 89, in __pthread_kill_internal
[move_group-4]     | Source "./nptl/pthread_kill.c", line 78, in __pthread_kill_implementation
[move_group-4]       Source "./nptl/pthread_kill.c", line 44, in __pthread_kill [0x79233a0969fc]
[move_group-4] Aborted (Signal sent by tkill() 43569 1000)
[ERROR] [move_group-4]: process has died [pid 43569, exit code -6, cmd '/home/sanmaster/ws_moveit/install/moveit_ros_move_group/lib/moveit_ros_move_group/move_group --ros-args --params-file /tmp/launch_params_q793jq7l'].
[rviz2-1] [ERROR] [1717116434.373774845] [rviz2.moveit.ros.motion_planning_frame]: Action server: /recognize_objects not available
[rviz2-1] [INFO] [1717116434.396707512] [rviz2.moveit.ros.motion_planning_frame]: MoveGroup namespace changed: / -> . Reloading params.
[rviz2-1] [INFO] [1717116434.439370432] [rviz2.moveit.ros.rdf_loader]: Loaded robot model in 0.0342068 seconds
[rviz2-1] [INFO] [1717116434.439454770] [rviz2.moveit.core.robot_model]: Loading robot model 'gen3'...
[rviz2-1] [INFO] [1717116434.439484754] [rviz2.moveit.core.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[rviz2-1] [INFO] [1717116434.851120679] [rviz2.moveit.ros.rdf_loader]: Loaded robot model in 0.00390296 seconds
[rviz2-1] [INFO] [1717116434.851172141] [rviz2.moveit.core.robot_model]: Loading robot model 'gen3'...
[rviz2-1] [INFO] [1717116434.851185580] [rviz2.moveit.core.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[rviz2-1] [INFO] [1717116434.997956622] [rviz2.moveit.kinematics.kdl_kinematics_plugin]: Joint weights for group 'manipulator': 1 1 1 1 1 1 1
[rviz2-1] [INFO] [1717116435.378397601] [rviz2.moveit.ros.planning_scene_monitor]: Starting planning scene monitor
[rviz2-1] [INFO] [1717116435.379453644] [rviz2.moveit.ros.planning_scene_monitor]: Listening to '/monitored_planning_scene'
[rviz2-1] [INFO] [1717116435.383643938] [rviz2.moveit.ros.planning_scene_monitor]: Starting planning scene monitor
[rviz2-1] [INFO] [1717116435.385660152] [rviz2.moveit.ros.planning_scene_monitor]: Listening to '/monitored_planning_scene'
[rviz2-1] [INFO] [1717116435.403134870] [interactive_marker_display_106863529226480]: Connected on namespace: /rviz_moveit_motion_planning_display/robot_interaction_interactive_marker_topic
[rviz2-1] [INFO] [1717116435.410506921] [rviz2.moveit.ros.robot_interaction]: No active joints or end effectors found for group 'gripper'. Make sure that kinematics.yaml is loaded in this node's namespace.
[rviz2-1] [INFO] [1717116435.412065736] [rviz2.moveit.ros.robot_interaction]: No active joints or end effectors found for group 'gripper'. Make sure that kinematics.yaml is loaded in this node's namespace.
[rviz2-1] [INFO] [1717116435.425536592] [interactive_marker_display_106863529226480]: Sending request for interactive markers
[rviz2-1] [INFO] [1717116435.442680896] [interactive_marker_display_106863529226480]: Service response received for initialization
[rviz2-1] [INFO] [1717116440.385022304] [rviz2.moveit.ros.planning_scene_monitor]: Failed to call service get_planning_scene, have you launched move_group or called psm.providePlanningSceneService()?
[rviz2-1] [INFO] [1717116440.416608265] [rviz2.moveit.ros.planning_scene_monitor]: Failed to call service get_planning_scene, have you launched move_group or called psm.providePlanningSceneService()?
[rviz2-1] [INFO] [1717116440.416694902] [rviz2.moveit.ros.motion_planning_frame]: group gripper
[rviz2-1] [INFO] [1717116440.416704810] [rviz2.moveit.ros.motion_planning_frame]: Constructing new MoveGroup connection for group 'gripper' in namespace ''

Any help would be greatly appreciated!

**Comment by Kaiser1401** [comment]
`[move_group-4] what(): expected [string_array] got [string]` seems to be because only ROS humble expects the parameter actually to be astring (not a string array)
--> Look at the [ompl_planning.yaml](https://github.com/Kinovarobotics/ros2_kortex/blob/main/kortex_moveit_config/kinova_gen3_7dof_robotiq_2f_85_moveit_config/config/ompl_planning.yaml#L7) and change the `request_adapters` to be a List accoring to the header meassage in the same file.

Had the same (and some) problems running the demo on Jazzy

**Comment by sea-bass** [comment]
Should be fixed by https://github.com/moveit/moveit2_tutorials/pull/921 -- please try it out!
