### ISSUE TITLE
ROS Jayyz broken demo due to changed parameter format

### ISSUE THREAD

**Issue by Kaiser1401** [moveit/moveit2_tutorials#911]
### Description

Expected configuration syntax and values changed for ROS2 Jazzy breaking the getting started demo

See:
[MoveIt2 issue #2854](https://github.com/moveit/moveit2/issues/2854) for details
[ros2_kortex issue #223](https://github.com/Kinovarobotics/ros2_kortex/issues/223)

### Your environment
* ROS Distro: Jazzy
* OS Version: Ubuntu 24.04
* Source, Main (bf94204)

### Steps to reproduce
Try geting started demo

**Comment by sea-bass** [comment]
Should be fixed by https://github.com/moveit/moveit2_tutorials/pull/921 -- please try it out!
