### ISSUE TITLE
Arm support for MoveIt ? 

### ISSUE THREAD

**Issue by nirbheeksetia** [moveit/moveit2_tutorials#986]
**Description**
I am trying to follow the official MoveIt installation tutorial from the website. (For further reference: https://moveit.picknik.ai/main/doc/tutorials/getting_started/getting_started.html ) While running the last command I get an error concerning the architecture of my system.

**Environment**
      -ROS Distro: Jazzy 
      -OS Version: Ubuntu 24.04 (WSL2)
      - CPU information:
      ![Image](https://github.com/user-attachments/assets/1795d795-b7a7-45e2-aae1-582d8f5ff745)

**Steps to reproduce**
After following through the whole tutorial, run the final command:
```
cd ~/ws_moveit
colcon build --mixin release
```

**Error/Output**
![Image](https://github.com/user-attachments/assets/6a9f258c-f6c0-4188-9a8b-8275cd314075)

Is there really no arm support for MoveIt? if yes, how do i fix this issue?

**Comment by sea-bass** [comment]
That seems related to the `ros2_kortex` repo.

You could maybe try this PR branch, which adds `aarch64` support?
https://github.com/Kinovarobotics/ros2_kortex/pull/238

**Comment by nirbheeksetia** [comment]
Allright, I will try that. Thank you for your answer!

**Comment by mikeferguson** [comment]
Agree - this appears to be a ros2_kortex issue, not MoveIt itself
